version: "3.9"

services:
  mongo:
    image: mongo
    container_name: coshopper-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME={$MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={$MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE={$MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./coshopper-backend
    container_name: coshopper-backend
    restart: unless-stopped
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://{$MONGO_INITDB_ROOT_USERNAME}:{$MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/{$MONGO_INITDB_DATABASE}
      - JWT_SECRET={$JWT_SECRET}
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./coshopper-frontend
    container_name: coshopper-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data: